import './globals.css'
import type { Metadata } from 'next'
import { Cinzel } from 'next/font/google'
import NavBar from '../components/NavBar'

const inter = Cinzel({ subsets: ['latin'],
weight:"400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-h-screen relative'>
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  )
}
